/**
 * Flashcards — spaced-repetition cards generated from a note by Claude, reviewed
 * and edited by the user, then stored per-note in the vault's internal data dir.
 *
 * Storage: one rich-JSON deck file per source note, under the vault's internal
 * `.zennotes/flashcards/` dir (`<notePath>.cards.json`). Because it is plain
 * JSON-over-file it works on BOTH backends (Electron fs + the web HTTP bridge)
 * by reusing the generic note file primitives — the same trick the web bridge
 * uses for CSV Databases. The user-facing CSV "Databases" feature is NOT reused:
 * flat-string cells can't hold nested concepts / prerequisites / FSRS state.
 *
 * This module is PURE (no node/DOM imports) so it is shared by the main process,
 * the renderer, and the web bridge. Two shapes matter: what Claude returns (a
 * `FlashcardDraft`) versus what is stored at rest (a `Flashcard` = draft +
 * identity + an initialized, reserved `srs` block so Phase 2's FSRS scheduler
 * needs no data migration).
 */

export const FLASHCARD_STORE_VERSION = 1

/** Internal vault dir holding deck files (mirrors `.zennotes/` app-data convention). */
export const FLASHCARDS_DIR = '.zennotes/flashcards'
/** Suffix appended to a note path to form its deck file path. */
export const DECK_FILE_SUFFIX = '.cards.json'

export type FlashcardKind = 'recall' | 'synthesis'

// Recall subtypes train retrieval of material explicit in the note.
// Synthesis subtypes train transfer — connecting the note to scenarios, other
// notes, or the real world. Full definitions in the "Card taxonomy" doc.
export type RecallSubtype =
  | 'cued' // Q→A direct retrieval
  | 'reverse' // description → name the concept
  | 'cloze' // fill-in-the-blank in a sentence from the note
  | 'enumeration' // free-recall a set ("list the N …")
  | 'sequence' // order steps / "what comes after k"
  | 'causeEffect' // directional causal link
export type SynthesisSubtype =
  | 'application' // apply the concept to a new concrete scenario
  | 'connection' // link to another note / domain
  | 'contradiction' // surface and resolve an apparent tension
  | 'critique' // limits, assumptions, failure conditions
  | 'analogy' // generate an analogy for the concept
  | 'prediction' // counterfactual / forward-looking reasoning
  | 'exampleGen' // produce your own instance of the concept

export const RECALL_SUBTYPES: readonly RecallSubtype[] = [
  'cued',
  'reverse',
  'cloze',
  'enumeration',
  'sequence',
  'causeEffect'
]
export const SYNTHESIS_SUBTYPES: readonly SynthesisSubtype[] = [
  'application',
  'connection',
  'contradiction',
  'critique',
  'analogy',
  'prediction',
  'exampleGen'
]

/** The FSRS rating every review funnels to (1 | 2 | 3 | 4). */
export type FsrsRating = 'again' | 'hard' | 'good' | 'easy'

// A structured rubric for grading open-ended (synthesis) answers. Generated by
// Claude, edited by the user at review, consumed by the study loop (Phase 2).
export interface RubricCriterion {
  id: string // stable uuid
  description: string // what a good answer must demonstrate (atomic)
  weight: number // relative points (1–3); used to compute a 0..1 score
}
export interface Rubric {
  criteria: RubricCriterion[] // 1–4 atomic criteria
  modelAnswer: string // an exemplar full-credit answer
  misconceptions?: string[] // common wrong turns — drive targeted feedback
}

// What Claude must return per card (validated/normalized before save).
export interface FlashcardDraft {
  kind: FlashcardKind
  subtype: RecallSubtype | SynthesisSubtype
  front: string // the prompt shown first
  back: string // recall: the answer | synthesis: a model answer
  // Grading payload — keyed by `kind` (see "Grading & rubric model"):
  acceptableAnswers?: string[] // recall ONLY: extra strings that also count as correct
  rubric?: Rubric // synthesis ONLY: REQUIRED for synthesis, absent for recall
  concepts: string[] // 1–3 labels; concepts[0] is the single FOCUS concept
  prerequisites: string[] // 1–3 concept labels needed first (free-text in P1)
  difficulty: 1 | 2 | 3 | 4 | 5
  sourceQuote?: string // verbatim span from the note (for "why I got this wrong")
}

// Reserved scheduling block, initialized at save so Phase 2 (FSRS) needs no migration.
export interface SrsState {
  state: 'new' | 'learning' | 'review' | 'relearning' // 'new' in P1
  due: string | null // ISO; null until first scheduled
  stability: number | null
  difficulty: number | null // FSRS difficulty (distinct from card difficulty above)
  reps: number // 0
  lapses: number // 0
  lastReview: string | null
}

export interface Flashcard extends FlashcardDraft {
  id: string // uuid
  srs: SrsState
  userEdited: boolean // true if the user changed it during review
  createdAt: number
  generatedBy: string // model id, e.g. 'claude-sonnet-4-6'
}

export interface FlashcardDeck {
  version: typeof FLASHCARD_STORE_VERSION
  sourceNotePath: string // vault-relative POSIX path of the note
  cards: Flashcard[]
}

/** Lightweight listing entry for deck discovery / the cross-deck index. */
export interface FlashcardDeckSummary {
  /** Vault-relative POSIX path of the source note. */
  sourceNotePath: string
  /** Vault-relative POSIX path of the deck file. */
  deckPath: string
  cardCount: number
}

// ---------------------------------------------------------------------------
// Grading & rubric records (defined now, consumed by the Phase 2 study loop).
// ---------------------------------------------------------------------------

export interface GradedCriterion {
  criterionId: string
  met: boolean
}
export interface ReviewGrade {
  cardId: string
  reviewedAt: string // ISO
  predictedRating: FsrsRating // calibration: self-prediction BEFORE reveal (same 1–4 scale)
  rating: FsrsRating // what FSRS consumes — actual self-grade AFTER reveal
  // synthesis only — self-assessment against the bulleted rubric:
  learnerAnswer?: string
  criteria?: GradedCriterion[] // which bullets the learner checked
  score?: number // 0..1, weighted by criterion weight
}

// ---------------------------------------------------------------------------
// Injectable id factory (main passes node's randomUUID; tests pass a counter).
// ---------------------------------------------------------------------------

export type GenId = () => string

export const defaultGenId: GenId = () => {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto
  if (c?.randomUUID) return c.randomUUID()
  return `c-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`
}

const toPosixPath = (p: string): string => p.replace(/\\/g, '/').replace(/^\/+/, '')

// ---------------------------------------------------------------------------
// Deck path helpers (deterministic, POSIX).
// ---------------------------------------------------------------------------

/** The deck file path for a note. e.g. `a/Note.md` → `.zennotes/flashcards/a/Note.md.cards.json`. */
export function deckPathForNote(notePath: string): string {
  return `${FLASHCARDS_DIR}/${toPosixPath(notePath)}${DECK_FILE_SUFFIX}`
}

/** The source note path for a deck file path, or null when it isn't a deck file. */
export function notePathFromDeckPath(deckPath: string): string | null {
  const p = toPosixPath(deckPath)
  const prefix = `${FLASHCARDS_DIR}/`
  if (!p.startsWith(prefix) || !p.endsWith(DECK_FILE_SUFFIX)) return null
  return p.slice(prefix.length, p.length - DECK_FILE_SUFFIX.length) || null
}

/** True for files that live inside the internal flashcards dir (hidden from the note list). */
export function isFlashcardInternalPath(relPath: string): boolean {
  const p = toPosixPath(relPath)
  return p === FLASHCARDS_DIR || p.startsWith(`${FLASHCARDS_DIR}/`)
}

/** The `{ from, to }` deck paths for a note rename/move (for the lifecycle hook). */
export function relocateDeckPath(
  oldNotePath: string,
  newNotePath: string
): { from: string; to: string } {
  return { from: deckPathForNote(oldNotePath), to: deckPathForNote(newNotePath) }
}

// ---------------------------------------------------------------------------
// Virtual tab-path helpers (mirror databases.ts). A review opens as a virtual
// tab keyed by the note path, so it never hits the markdown pipeline but the
// path stays recoverable for the renderer.
// ---------------------------------------------------------------------------

const FLASHCARDS_TAB_PREFIX = 'zen://flashcards/'

export function flashcardsTabPath(notePath: string): string {
  return `${FLASHCARDS_TAB_PREFIX}${encodeURIComponent(toPosixPath(notePath))}`
}

export function isFlashcardsTabPath(path: string | null | undefined): boolean {
  return typeof path === 'string' && path.startsWith(FLASHCARDS_TAB_PREFIX)
}

export function notePathFromFlashcardsTab(path: string | null | undefined): string | null {
  if (!path || !isFlashcardsTabPath(path)) return null
  const encoded = path.slice(FLASHCARDS_TAB_PREFIX.length)
  if (!encoded) return null
  try {
    return decodeURIComponent(encoded)
  } catch {
    return encoded
  }
}

/** Display title for a flashcards tab (the source note's basename). */
export function flashcardsTitleFromTab(path: string | null | undefined): string {
  const note = notePathFromFlashcardsTab(path)
  if (!note) return 'Flashcards'
  const base = note.split('/').filter(Boolean).pop() ?? note
  return base.replace(/\.md$/i, '')
}

// ---------------------------------------------------------------------------
// Defensive normalization of Claude output (mirror dbNormalizeSidecar).
// ---------------------------------------------------------------------------

const asString = (v: unknown): string => (typeof v === 'string' ? v : '')
const trimmed = (v: unknown): string => asString(v).trim()

/** Clamp a free-text label list to 1–3 non-empty, deduped, trimmed entries. */
function clampLabels(raw: unknown): string[] {
  if (!Array.isArray(raw)) return []
  const out: string[] = []
  for (const item of raw) {
    const s = trimmed(item)
    if (s && !out.includes(s)) out.push(s)
    if (out.length >= 3) break
  }
  return out
}

/** Normalize an answer-string list: trim, drop empties, dedupe. */
function normalizeAnswers(raw: unknown): string[] {
  if (!Array.isArray(raw)) return []
  const out: string[] = []
  for (const item of raw) {
    const s = trimmed(item)
    if (s && !out.includes(s)) out.push(s)
  }
  return out
}

function clampDifficulty(raw: unknown): 1 | 2 | 3 | 4 | 5 {
  const n = Math.round(Number(raw))
  if (!Number.isFinite(n)) return 3
  return Math.min(5, Math.max(1, n)) as 1 | 2 | 3 | 4 | 5
}

/** Validate + normalize a rubric; returns null when it can't satisfy the contract. */
function normalizeRubric(raw: unknown, genId: GenId): Rubric | null {
  if (!raw || typeof raw !== 'object') return null
  const r = raw as Record<string, unknown>
  const modelAnswer = trimmed(r.modelAnswer)
  if (!modelAnswer) return null
  const rawCriteria = Array.isArray(r.criteria) ? r.criteria : []
  const criteria: RubricCriterion[] = []
  for (const c of rawCriteria) {
    if (!c || typeof c !== 'object') continue
    const cc = c as Record<string, unknown>
    const description = trimmed(cc.description)
    const weight = Number(cc.weight)
    if (!description || !Number.isFinite(weight) || weight <= 0) continue
    criteria.push({
      id: trimmed(cc.id) || genId(),
      description,
      weight: Math.min(3, Math.max(1, Math.round(weight)))
    })
    if (criteria.length >= 4) break
  }
  if (criteria.length === 0) return null
  const misconceptions = normalizeAnswers(r.misconceptions)
  const rubric: Rubric = { criteria, modelAnswer }
  if (misconceptions.length) rubric.misconceptions = misconceptions
  return rubric
}

/**
 * Defensive parse of one Claude card object. Enforces the atomicity + grading
 * contract: a valid `subtype` for its `kind`, non-empty front/back, 1–3
 * concepts/prerequisites, clamped difficulty, a valid `Rubric` on synthesis
 * cards (and NO rubric on recall cards). Returns null to DROP an invalid card.
 */
export function normalizeDraft(raw: unknown, genId: GenId = defaultGenId): FlashcardDraft | null {
  if (!raw || typeof raw !== 'object') return null
  const o = raw as Record<string, unknown>

  const kind = o.kind === 'synthesis' ? 'synthesis' : o.kind === 'recall' ? 'recall' : null
  if (!kind) return null

  const subtype = trimmed(o.subtype)
  const validSubtype =
    kind === 'recall'
      ? (RECALL_SUBTYPES as readonly string[]).includes(subtype)
      : (SYNTHESIS_SUBTYPES as readonly string[]).includes(subtype)
  if (!validSubtype) return null

  const front = trimmed(o.front)
  const back = trimmed(o.back)
  if (!front || !back) return null

  const concepts = clampLabels(o.concepts)
  if (concepts.length === 0) return null
  const prerequisites = clampLabels(o.prerequisites)

  const draft: FlashcardDraft = {
    kind,
    subtype: subtype as RecallSubtype | SynthesisSubtype,
    front,
    back,
    concepts,
    prerequisites,
    difficulty: clampDifficulty(o.difficulty)
  }

  const sourceQuote = trimmed(o.sourceQuote)
  if (sourceQuote) draft.sourceQuote = sourceQuote

  if (kind === 'synthesis') {
    const rubric = normalizeRubric(o.rubric, genId)
    if (!rubric) return null // synthesis MUST carry a valid rubric
    draft.rubric = rubric
  } else {
    // Recall cards must NOT carry a rubric; acceptableAnswers is optional.
    const acceptable = normalizeAnswers(o.acceptableAnswers)
    if (acceptable.length) draft.acceptableAnswers = acceptable
  }

  return draft
}

/** A fresh, unscheduled `SrsState` (`state:'new'`) — initialized at save time. */
export function newSrsState(): SrsState {
  return {
    state: 'new',
    due: null,
    stability: null,
    difficulty: null,
    reps: 0,
    lapses: 0,
    lastReview: null
  }
}

/** Promote a reviewed draft to a stored card with identity + initialized srs. */
export function draftToCard(
  draft: FlashcardDraft,
  model: string,
  opts: { userEdited?: boolean; genId?: GenId; now?: number } = {}
): Flashcard {
  const genId = opts.genId ?? defaultGenId
  return {
    ...draft,
    id: genId(),
    srs: newSrsState(),
    userEdited: opts.userEdited ?? false,
    createdAt: opts.now ?? Date.now(),
    generatedBy: model
  }
}

export function emptyDeck(notePath: string): FlashcardDeck {
  return { version: FLASHCARD_STORE_VERSION, sourceNotePath: toPosixPath(notePath), cards: [] }
}

/** Cross-deck index: cardId → its card + the note it came from (used in Phase 2). */
export function buildCardIndex(
  decks: FlashcardDeck[]
): Record<string, { card: Flashcard; sourceNotePath: string }> {
  const index: Record<string, { card: Flashcard; sourceNotePath: string }> = {}
  for (const deck of decks) {
    for (const card of deck.cards) {
      index[card.id] = { card, sourceNotePath: deck.sourceNotePath }
    }
  }
  return index
}

// ---------------------------------------------------------------------------
// Grading helpers (pure; ship now, used by the Phase 2 study loop).
// ---------------------------------------------------------------------------

/** Weighted fraction of rubric criteria the learner met → a 0..1 score. */
export function scoreRubric(rubric: Rubric, criteria: GradedCriterion[]): number {
  const total = rubric.criteria.reduce((sum, c) => sum + c.weight, 0)
  if (total <= 0) return 0
  const metById = new Map(criteria.map((c) => [c.criterionId, c.met]))
  const earned = rubric.criteria.reduce(
    (sum, c) => sum + (metById.get(c.id) ? c.weight : 0),
    0
  )
  return earned / total
}

/** Map a 0..1 rubric score to a suggested FSRS rating (pure threshold). */
export function scoreToRating(score: number): FsrsRating {
  if (score < 0.25) return 'again'
  if (score < 0.6) return 'hard'
  if (score < 0.9) return 'good'
  return 'easy'
}

const normalizeAnswerText = (s: string): string =>
  s.trim().toLowerCase().replace(/\s+/g, ' ')

/** Auto-check assist for recall cards: typed answer vs. back + acceptableAnswers. */
export function checkRecallAnswer(
  typed: string,
  back: string,
  acceptableAnswers: string[] = []
): boolean {
  const t = normalizeAnswerText(typed)
  if (!t) return false
  const candidates = [back, ...acceptableAnswers].map(normalizeAnswerText)
  return candidates.includes(t)
}
